set hls
set number
set ic
set showcmd
nnoremap <Left> :echo"սխ ա լ ստ եղն "<CR>
nnoremap <Right> :echo"սխ ա լ ստ եղն "<CR>
nnoremap <Up> :echo"սխ ա լ ստ եղն "<CR>
nnoremap <Down> :echo"սխ ա լ ստ եղն "<CR>
inoremap <C-S> <ESC>:w!<CR>i
call plug#begin('~/.vim/plugged')
Plug 'preservim/nerdtree'
call plug#end()
noremap <C-N> :NERDTreeToggle<CR>
